# base image
FROM openjdk:11

#Maintainer
LABEL maintainer="javaguides.net"

#Copy the jar
ADD target/docker-0.0.1-SNAPSHOT.jar sprigboot-docker-demo.jar

ENTRYPOINT ["java", "-jar", "sprigboot-docker-demo.jar"]
